# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-29 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='titile',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
